DROP TABLE IF EXISTS players CASCADE;
CREATE TABLE players (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  room_id INTEGER REFERENCES rooms(id) ON DELETE CASCADE,
  player_position INTEGER
);